# Generated by Django 4.2.6 on 2023-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plant', models.CharField(max_length=200)),
                ('type_plant', models.CharField(max_length=50)),
                ('price_plant', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('img_plant', models.ImageField(upload_to='')),
                ('text_plant', models.TextField()),
            ],
        ),
    ]
