# Generated by Django 4.2.4 on 2023-10-15 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0003_alter_plant_img_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='sale_plant',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='img_plant',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name_plant',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price_plant',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='text_plant',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(max_length=50, verbose_name='Вид растения'),
        ),
    ]
