# Generated by Django 4.2.6 on 2023-10-19 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0004_plant_sale_plant_alter_plant_img_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price_plant',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('ДЛР', 'Декоративно-лиственные растения'), ('Кактусы и суккуленты', 'Кактусы и суккуленты'), ('КЦР', 'Красиво-цветущие растения')], max_length=50, verbose_name='Вид растения'),
        ),
    ]
