# Generated by Django 4.2.6 on 2023-10-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0006_question_alter_plant_type_plant_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('Кактусы и суккуленты', 'Кактусы и суккуленты'), ('Красиво-цветущие растения', 'Красиво-цветущие растения'), ('Декоративно-лиственные растения', 'Декоративно-лиственные растения')], max_length=50, verbose_name='Вид растения'),
        ),
    ]
