# Generated by Django 4.2.6 on 2023-10-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0007_alter_plant_type_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('Красиво-цветущие растения', 'Красиво-цветущие растения'), ('Кактусы и суккуленты', 'Кактусы и суккуленты'), ('Декоративно-лиственные растения', 'Декоративно-лиственные растения')], max_length=50, verbose_name='Вид растения'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
