# Generated by Django 4.2.6 on 2023-10-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0009_alter_plant_type_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('Красиво-цветущие растения', 'Красиво-цветущие растения'), ('Декоративно-лиственные растения', 'Декоративно-лиственные растения'), ('Кактусы и суккуленты', 'Кактусы и суккуленты')], max_length=50, verbose_name='Вид растения'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_home.question')),
            ],
        ),
    ]
