# Generated by Django 4.2.6 on 2023-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0013_quiz_alter_plant_type_plant_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='categoty_name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='question',
            name='img_bg',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Картинка для вопроса'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('Декоративно-лиственные растения', 'Декоративно-лиственные растения'), ('Красиво-цветущие растения', 'Красиво-цветущие растения'), ('Кактусы и суккуленты', 'Кактусы и суккуленты')], max_length=50, verbose_name='Вид растения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
