# Generated by Django 4.2.6 on 2023-10-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0014_rename_categoty_name_quiz_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('Декоративно-лиственные растения', 'Декоративно-лиственные растения'), ('Кактусы и суккуленты', 'Кактусы и суккуленты'), ('Красиво-цветущие растения', 'Красиво-цветущие растения')], max_length=50, verbose_name='Вид растения'),
        ),
    ]
