# Generated by Django 4.2.6 on 2023-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0015_alter_answer_is_correct_alter_plant_type_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.AddField(
            model_name='answer',
            name='score_ans',
            field=models.IntegerField(choices=[(3, 'Q3'), (1, 'Q1'), (2, 'Q2')], default=1, verbose_name='Вариант ответа'),
        ),
    ]
