# Generated by Django 4.2.6 on 2023-11-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0016_remove_question_marks_answer_score_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score_ans',
            field=models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')], default=1, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('Декоративно-лиственные растения', 'Декоративно-лиственные растения'), ('Красиво-цветущие растения', 'Красиво-цветущие растения'), ('Кактусы и суккуленты', 'Кактусы и суккуленты')], max_length=50, verbose_name='Вид растения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test', to='main_home.quiz', verbose_name='Категория'),
        ),
    ]
