# Generated by Django 4.2.6 on 2023-11-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0017_alter_answer_score_ans_alter_plant_type_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score_ans',
            field=models.IntegerField(choices=[(3, 'Q3'), (1, 'Q1'), (2, 'Q2')], default=1, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type_plant',
            field=models.CharField(choices=[('Декоративно-лиственные растения', 'Декоративно-лиственные растения'), ('Кактусы и суккуленты', 'Кактусы и суккуленты'), ('Красиво-цветущие растения', 'Красиво-цветущие растения')], max_length=50, verbose_name='Вид растения'),
        ),
    ]
