# Generated by Django 4.2.6 on 2023-11-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='ProductPlant',
        ),
    ]
